#![warn(missing_docs)]
//! Top-level windows, pane tree, tab strip, find bar, command palette,
//! and the per-window message pump.
//!
//! The only crate that touches HWNDs.

pub mod buffer_history_tab;
mod caret_tween;
pub mod chord_hud;
mod chord_hud_render;
mod chrome_motion;
mod display_prewarm_cache;
mod edit_pulse;
mod edit_trace;
pub mod error;
pub mod file_io;
mod file_io_directory;
mod file_io_primitives;
mod file_io_worker;
mod file_tree;
pub mod find_bar;
mod find_bar_memento;
pub mod find_in_all;
mod find_regex_help;
mod find_replace_plan;
mod find_scope;
mod focus_change_trace;
pub mod font_picker;
mod footnote_hover;
pub mod goto_overlay;
pub mod hex_picker;
pub mod image_store;
mod jump_glow;
mod live_reload;
mod memory_trace;
mod motion;
pub mod mouse;
pub mod overlay_render;
mod overlay_render_find;
mod overlay_render_goto;
mod overlay_render_palette;
mod overlay_render_pickers;
pub mod overlays;
mod paint_trace;
mod paint_trace_context;
mod paint_trace_stack;
mod paint_trace_summary;
mod paint_trace_wndproc_names;
pub mod palette;
pub mod palette_math;
pub mod palette_mode;
mod palette_rank;
pub mod pane_layout;
pub mod pane_shortcuts;
pub mod pane_splitter;
pub mod pane_state;
pub mod pane_tree;
pub mod pane_tree_codec;
mod pane_tree_codec_ids;
mod pane_tree_codec_nodes;
pub mod pane_tree_kind;
mod pane_tree_label;
pub mod previous_buffer_browser;
mod process_trace;
mod projection_worker;
/// Projection-worker probes used by integration tests.
#[doc(hidden)]
pub mod projection_worker_test_support;
pub mod quick_open;
pub mod search_minimap;
mod selection;
mod selection_arithmetic;
mod selection_byte_helpers;
mod selection_dispatch;
mod selection_motion_cache;
mod selection_vertical;
pub mod slash_palette;
mod smart_paste;
mod status_motion;
mod surface_motion;
pub mod tab_hover;
pub mod tab_switcher;
pub mod text_input;
pub mod theme_picker;
pub mod view_overlay;
pub mod window;
mod window_activation_grace;
pub mod window_auto_pair;
mod window_background_throttle;
mod window_buffer_history_tab;
mod window_buffer_history_tab_input;
mod window_buffer_tab_repair;
mod window_caret_anchor;
mod window_caret_row_index;
mod window_click_trace;
pub mod window_clipboard;
mod window_clipboard_image;
mod window_close_confirm;
mod window_code_copy_hover;
mod window_commanding;
pub mod window_config;
mod window_constants;
mod window_context_menu;
pub mod window_control;
mod window_decoration;
mod window_decoration_prune;
mod window_decoration_watchdog;
mod window_diagnostics;
mod window_dismiss;
mod window_dispatch;
mod window_display_prewarm;
mod window_dpi;
mod window_file;
mod window_file_context;
mod window_file_dialogs;
mod window_file_image_drop;
mod window_file_open;
mod window_file_save;
mod window_file_tree;
mod window_find_replace;
mod window_find_scope;
mod window_find_target;
mod window_focus;
mod window_fold_click;
mod window_font_picker;
mod window_font_swap;
mod window_footnote_hover;
mod window_heading_lines_cache;
mod window_helpers;
mod window_hex_palette;
mod window_image_animation;
mod window_image_placements;
pub mod window_ime;
mod window_indent;
mod window_input_modifiers;
mod window_keymap_reload;
mod window_link_clipboard;
mod window_loading_overlay;
mod window_markdown_inline;
mod window_markdown_table_nav;
mod window_markdown_table_ops;
mod window_metrics_paint;
mod window_minimap;
mod window_motion;
mod window_mouse;
mod window_mouse_autoscroll;
mod window_mouse_cursor;
mod window_mouse_hit_test;
mod window_mouse_hit_test_cache;
mod window_mouse_hover;
mod window_mouse_scrollbar;
mod window_mouse_segment_hit;
mod window_mouse_splitter;
mod window_mouse_table_resize;
mod window_mouse_tabs;
mod window_new;
mod window_outline;
mod window_outline_entries_cache;
mod window_outline_resize;
mod window_overlay_click;
mod window_overlay_confirm;
mod window_overlay_input;
mod window_overlays;
mod window_overlays_input_op;
mod window_paint;
mod window_paint_builders;
mod window_paint_selection_reveal;
mod window_paint_setup;
mod window_paint_spectators;
mod window_paint_trace;
mod window_paint_viewport_rows;
mod window_pane_layout_ops;
pub mod window_pane_modes;
mod window_pane_state_mirror;
mod window_panes;
mod window_placement_apply;
pub mod window_placement_persistence;
pub mod window_previous_buffer_browser;
mod window_projection_early_dispatch;
mod window_projection_plan;
mod window_projection_spectator;
mod window_projection_worker;
mod window_registry;
mod window_renderer_lifecycle;
mod window_resize_fence;
mod window_right_edge_chrome;
mod window_row_index_cache;
mod window_row_splice;
mod window_run;
mod window_runtime;
mod window_scroll;
mod window_search;
mod window_settings_persist;
mod window_settings_projections;
pub mod window_settings_reload;
mod window_settings_seed;
mod window_slash_palette;
mod window_spectator_cache;
pub mod window_spell;
mod window_startup_open;
mod window_status_bar;
mod window_status_bar_idle;
mod window_status_bar_line_ending;
mod window_status_chips;
mod window_status_notice;
mod window_surround_on_type;
mod window_tab_drag;
mod window_tab_drag_ghost;
mod window_tab_drag_overlay;
mod window_tab_overlay;
mod window_tab_pin;
mod window_tab_step;
mod window_theme;
mod window_theme_apply;
mod window_theme_atomic_write;
mod window_theme_manage;
mod window_theme_settings_edit;
pub mod window_time_machine;
pub mod window_time_machine_hud;
mod window_time_machine_ops;
pub mod window_timers;
mod window_titlebar;
mod window_trace_state;
mod window_trace_summary_timer;
mod window_tutorial;
mod window_view;
mod window_view_context;
mod window_view_options;
mod window_view_toggles;
mod window_view_zoom;

pub use error::Error;
pub use file_io_directory::{DirectoryEntry, DirectoryEntryKind};
pub use live_reload::LiveReload;
pub use overlays::{OverlayKind, Overlays};
pub use window::Window;
pub use window_config::{WindowCommands, WindowConfig};
pub use window_control::{WindowControl, WindowControlRx, WindowControlTx};
pub use window_placement_persistence::{RestoredState, WindowPersistence, WindowStateSnapshot};
