//! Tutorial-tab open / focus.
//!
//! Mirrors the metrics-buffer flow in [`crate::window_time_machine`] —
//! "open or focus a buffer that already exists; allocate it the first
//! time" — but routes through
//! [`continuity_buffer::Buffer::synthetic_read_only`] so the buffer is
//! never persisted and rejects all edits before they reach the rope.
//!
//! Thread ownership: UI thread (owner of [`crate::Window`]).

use continuity_buffer::Buffer;
use continuity_command::TUTORIAL_MD;

use crate::Window;

impl Window {
    /// Open (or focus) the tutorial tab in this window.
    ///
    /// First call constructs a synthetic, read-only [`Buffer`] populated
    /// with the embedded `TUTORIAL_MD` (auto-generated by
    /// `cargo xtask gen-tutorial`), adopts it through
    /// [`continuity_core::EditorHandle::adopt_buffer`], pins its id in
    /// `view_options.tutorial_buffer_id`, and opens it as a tab in the
    /// focused pane. The synthetic flag tells core to skip the
    /// `persist.touch_buffer` write so no `buffers` row is created.
    ///
    /// Subsequent calls reuse the existing buffer: if the tab is still
    /// open, [`Window::focus_existing_tab_for`] re-activates it; if the
    /// user closed it, [`Window::adopt_buffer_as_new_tab`] re-installs
    /// the buffer as a fresh tab. Either way the user lands on the
    /// tutorial.
    pub(crate) fn show_tutorial_buffer_impl(&mut self) -> Result<(), crate::Error> {
        if let Some(id) = self.view_options.tutorial_buffer_id {
            if !self.focus_existing_tab_for(id) {
                self.adopt_buffer_as_new_tab(id);
            }
            self.request_repaint();
            return Ok(());
        }

        // First invocation: construct the synthetic buffer, adopt it
        // through the core thread (no persist writes — see
        // `crates/core/src/handle.rs::AdoptBuffer`), pin its id, and
        // open as a new tab.
        let buffer = Buffer::synthetic_read_only(TUTORIAL_MD);
        let id = self.editor.adopt_buffer(buffer, 1, 0);
        self.view_options.tutorial_buffer_id = Some(id);
        self.adopt_buffer_as_new_tab(id);
        self.request_repaint();
        Ok(())
    }

    /// First-launch tutorial open. No-op when `enabled` is `false`;
    /// otherwise calls [`Self::show_tutorial_buffer_impl`] and logs
    /// (rather than propagates) any failure so a corrupted tutorial
    /// asset never blocks window startup.
    pub(crate) fn maybe_open_tutorial_on_first_launch(&mut self, enabled: bool) {
        if !enabled {
            return;
        }
        if let Err(e) = self.show_tutorial_buffer_impl() {
            eprintln!("continuity: tutorial open on first launch failed: {e}");
        }
    }
}
