//! Timeline, metrics, tutorial, and history-tab `ViewContext` methods.

macro_rules! view_context_timeline_metrics_methods {
    () => {
        // ---- δ.4 — previous-buffer browser ----

        /// δ.4: open the previous-buffer browser overlay. Lists every
        /// buffer in the persist DB (closed tabs included, trash excluded
        /// by default) so the user can reopen a closed buffer beyond the
        /// single-step `tab.reopen_closed` history.
        fn show_previous_buffer_browser(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("show_previous_buffer_browser"))
        }

        /// δ.4: open the time-machine slider against a specific closed
        /// buffer (driven by the previous-buffer browser's inline action).
        /// Default impl errors — only `ui::Window` overrides.
        fn open_timeline_for_closed_buffer(
            &mut self,
            _buffer_id: continuity_buffer::BufferId,
        ) -> Result<(), Error> {
            Err(Error::UnsupportedContext("open_timeline_for_closed_buffer"))
        }

        // ---- Phase I1 — time-machine slider + named snapshots ----

        /// §I1: open the buffer-timeline overlay — drag-slider preview of
        /// past revisions; `Enter` commits as a content-replace edit.
        fn open_buffer_timeline(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("open_buffer_timeline"))
        }

        /// §I1: stamp the supplied `label` onto the next snapshot the
        /// editor commits for the active buffer. The label surfaces on the
        /// time-machine slider's tick marks. An empty `label` clears any
        /// pending label.
        fn mark_next_snapshot(&mut self, _label: &str) -> Result<(), Error> {
            Err(Error::UnsupportedContext("mark_next_snapshot"))
        }

        // ---- Phase I2 — WPM + activity heatmap buffer ----

        /// §I2: open (or focus) the dedicated metrics buffer as a new tab
        /// in the focused pane. The buffer renders a 90-day calendar-style
        /// heatmap + rolling WPM sparkline + top buffers by edit count
        /// this week. Updates 1 Hz while it is the active tab.
        fn show_metrics_buffer(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("show_metrics_buffer"))
        }

        /// §I2: drop every row in `metrics_daily`. Backs the user-facing
        /// `metrics.purge` command.
        fn purge_metrics(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("purge_metrics"))
        }

        /// Open (or focus) the tutorial tab — synthetic read-only buffer
        /// rendered through the normal markdown pipeline. Content lives
        /// in `crates/command/assets/tutorial.md` (regenerated by
        /// `cargo xtask gen-tutorial`).
        fn show_tutorial_buffer(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("show_tutorial_buffer"))
        }

        /// Open (or focus) the buffer-history swimlane tab. Custom
        /// renderer; does not reuse the markdown paint path.
        fn show_buffer_history_tab(&mut self) -> Result<(), Error> {
            Err(Error::UnsupportedContext("show_buffer_history_tab"))
        }
    };
}
