//! Help-surface commands.
//!
//! Currently the single command is `help.tutorial` — opens the
//! auto-generated tutorial as a synthetic read-only buffer in a new
//! tab in the focused pane. Content is produced by
//! `cargo xtask gen-tutorial` (see `xtask/src/tutorial_gen.rs`) and
//! embedded by `crates/app/assets/tutorial.md`.
//!
//! Sibling of [`crate::view_timeline_metrics`] — same shape as
//! `view.metrics` (open-or-focus a synthetic buffer as a tab), just
//! routed through the dedicated [`crate::ViewContext::show_tutorial_buffer`]
//! method.

use std::sync::Arc;

use crate::{CommandId, ContextPredicate, Registry};

/// Command id for opening the tutorial tab.
pub const HELP_TUTORIAL: CommandId = CommandId("help.tutorial");

/// Embedded markdown source of the tutorial buffer.
///
/// Auto-generated by `cargo xtask gen-tutorial` from
/// `.docs/design/features/*.md` and `crates/keymap/assets/default.toml`.
/// Embedded at compile time via `include_str!` so the binary is fully
/// portable — no runtime file-system lookup, no schema migration to
/// seed it. Consumers (e.g. `ui::Window::show_tutorial_buffer_impl`)
/// read this constant and feed it to
/// [`continuity_buffer::Buffer::synthetic_read_only`].
pub const TUTORIAL_MD: &str = include_str!("../assets/tutorial.md");

/// Register every help-surface command.
///
/// `help.tutorial` is `palette_safe = true` because the tutorial buffer
/// is read-only — running it from the slash palette can never cause
/// unintended edits.
pub fn register_help_commands(registry: &mut Registry) {
    let focused = ContextPredicate::parse("editor.focused");
    registry.register_palette_safe(
        HELP_TUTORIAL,
        focused,
        Arc::new(|_args, ctx| ctx.show_tutorial_buffer()),
    );
    registry.set_description(
        HELP_TUTORIAL,
        "Open the tutorial as a read-only tab — covers every feature, hotkey, and command (auto-generated from the docs)",
    );
}

#[cfg(test)]
mod tests {
    use std::cell::Cell;

    use super::*;
    use crate::{Context, Error};

    #[derive(Default)]
    struct StubCtx {
        tutorial_calls: Cell<u32>,
    }
    impl Context for StubCtx {
        fn lookup(&self, key: &str) -> Option<&str> {
            (key == "editor.focused").then_some("true")
        }
    }
    impl crate::FindContext for StubCtx {}
    impl crate::ViewContext for StubCtx {
        fn show_tutorial_buffer(&mut self) -> Result<(), Error> {
            self.tutorial_calls.set(self.tutorial_calls.get() + 1);
            Ok(())
        }
    }

    fn make_registry() -> Registry {
        let mut reg = Registry::new();
        register_help_commands(&mut reg);
        reg
    }

    #[test]
    fn help_tutorial_command_is_registered() {
        let reg = make_registry();
        let mut ctx = StubCtx::default();
        reg.dispatch(HELP_TUTORIAL, &serde_json::Value::Null, &mut ctx)
            .unwrap();
        assert_eq!(ctx.tutorial_calls.get(), 1);
    }

    #[test]
    fn help_tutorial_has_palette_description() {
        let reg = make_registry();
        let description = reg.description(HELP_TUTORIAL.0).unwrap();
        assert!(description.contains("tutorial"));
        assert!(description.contains("read-only"));
    }

    #[test]
    fn help_tutorial_is_palette_safe() {
        let reg = make_registry();
        assert!(reg.is_palette_safe(HELP_TUTORIAL.0));
    }
}
