//! Generated documentation subsystem for `.docs/generated/`.
//!
//! The generator owns high-churn mechanical facts: workspace package
//! inventories, compact file health, command/keymap tables, and settings
//! fields. Handwritten docs keep design intent and route to this surface.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

mod api;
mod commands;
mod gates;
mod inventory;
mod markdown_paths;
mod messages;
mod modules;
mod persist_schema;
mod repo_map;
mod rust_source;
mod selection_edits;
mod settings;
mod structured;
mod test_index;
mod theme_keys;

pub(crate) const GENERATED_DIR: &str = ".docs/generated";
pub(crate) const HEADER: &str =
    "<!-- Auto-generated by `cargo xtask docs`. Do not edit manually. -->";
const LINE_CAP: usize = 600;

pub(crate) type GeneratedDocs = BTreeMap<String, String>;

/// Regenerate `.docs/generated/` on disk.
pub fn run_write() -> Result<()> {
    let workspace = workspace_root()?;
    let docs = generate(&workspace)?;
    validate_generated_headers(&docs)?;
    validate_generated_line_cap(&docs)?;
    write_generated_docs(&workspace, &docs)?;
    markdown_paths::validate(&workspace)?;
    println!(
        "xtask docs: wrote {} generated doc file(s) to {}",
        docs.len(),
        GENERATED_DIR
    );
    Ok(())
}

/// Regenerate in memory, compare with disk, and fail on drift.
pub fn run_check() -> Result<()> {
    check()?;
    println!("xtask docs-check: generated docs are in sync");
    Ok(())
}

/// Silent generated-doc check for task compositions that own stdout.
pub fn check() -> Result<()> {
    let workspace = workspace_root()?;
    let docs = generate(&workspace)?;
    validate_generated_headers(&docs)?;
    validate_generated_line_cap(&docs)?;
    check_on_disk(&workspace, &docs)?;
    markdown_paths::validate(&workspace)?;
    Ok(())
}

pub(crate) fn generate(workspace: &Path) -> Result<GeneratedDocs> {
    let workspace_inventory = inventory::WorkspaceInventory::collect(workspace)?;
    let workspace_crates = rust_source::workspace_crates(workspace)?;
    let structured_index = structured::build(workspace, &workspace_crates)?;
    let mut docs = GeneratedDocs::new();
    docs.insert("README.md".into(), write_readme());
    docs.insert(
        "index.json".into(),
        structured::write_index_json(&structured_index)?,
    );
    docs.insert(
        "REPO_MAP.md".into(),
        repo_map::write_repo_map(&structured_index),
    );
    docs.insert(
        "FILE_TREE.md".into(),
        inventory::write_file_tree(&workspace_inventory),
    );
    docs.insert(
        "CRATES.md".into(),
        inventory::write_crates(&workspace_inventory),
    );
    docs.insert(
        "FILE_HEALTH.md".into(),
        inventory::write_file_health(&workspace_inventory),
    );
    docs.insert("COMMANDS.md".into(), commands::write_commands(workspace)?);
    docs.insert("SETTINGS.md".into(), settings::write_settings(workspace)?);
    docs.insert("GATES.md".into(), gates::write_gates(workspace)?);
    docs.insert(
        "TEST_INDEX.md".into(),
        test_index::write_test_index(workspace)?,
    );
    docs.insert(
        "THEME_KEYS.md".into(),
        theme_keys::write_theme_keys(workspace)?,
    );
    docs.insert(
        "PERSIST_SCHEMA.md".into(),
        persist_schema::write_persist_schema(workspace)?,
    );
    docs.insert("MESSAGES.md".into(), messages::write_messages(workspace)?);
    docs.insert(
        "SELECTION_EDITS.md".into(),
        selection_edits::write_selection_edits(workspace)?,
    );
    for krate in workspace_crates
        .into_iter()
        .filter(|krate| krate.path.starts_with("crates/"))
    {
        docs.insert(
            format!("modules/{}.md", krate.member),
            modules::write_modules(workspace, &krate)?,
        );
        docs.insert(
            format!("api/{}.md", krate.member),
            api::write_api(workspace, &krate)?,
        );
        docs.insert(
            format!("symbols/{}.md", krate.member),
            repo_map::write_symbols_for_crate(&structured_index, &krate.member),
        );
    }
    Ok(docs)
}

pub(crate) fn workspace_root() -> Result<PathBuf> {
    let manifest = std::env::var("CARGO_MANIFEST_DIR")
        .context("CARGO_MANIFEST_DIR not set (run via cargo)")?;
    let dir = PathBuf::from(manifest);
    let parent = dir
        .parent()
        .ok_or_else(|| anyhow::anyhow!("xtask manifest dir has no parent"))?;
    Ok(parent.to_path_buf())
}

fn write_generated_docs(workspace: &Path, docs: &GeneratedDocs) -> Result<()> {
    let generated_dir = workspace.join(GENERATED_DIR);
    fs::create_dir_all(&generated_dir)
        .with_context(|| format!("creating generated docs dir {}", generated_dir.display()))?;
    for (relative, content) in docs {
        let path = generated_dir.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating generated docs dir {}", parent.display()))?;
        }
        fs::write(&path, content)
            .with_context(|| format!("writing generated doc {}", path.display()))?;
    }
    remove_stale_generated_files(&generated_dir, docs)?;
    Ok(())
}

fn check_on_disk(workspace: &Path, docs: &GeneratedDocs) -> Result<()> {
    let generated_dir = workspace.join(GENERATED_DIR);
    let actual = generated_files(&generated_dir)?;
    let expected: BTreeSet<String> = docs.keys().cloned().collect();
    if let Some(stale) = actual.difference(&expected).next() {
        bail!(
            "generated docs stale file detected at {}/{}. Run `cargo xtask docs`.",
            GENERATED_DIR,
            stale
        );
    }
    for (relative, generated) in docs {
        let path = generated_dir.join(relative);
        let on_disk = fs::read_to_string(&path)
            .with_context(|| format!("reading generated doc {}", path.display()))?;
        validate_generated_marker(relative, &on_disk)?;
        if &on_disk != generated {
            bail!(
                "generated docs drift detected at {}/{} (on-disk = {} bytes, regenerated = {} bytes). Run `cargo xtask docs`.",
                GENERATED_DIR,
                relative,
                on_disk.len(),
                generated.len()
            );
        }
    }
    Ok(())
}

fn remove_stale_generated_files(generated_dir: &Path, docs: &GeneratedDocs) -> Result<()> {
    let expected: BTreeSet<String> = docs.keys().cloned().collect();
    for relative in generated_files(generated_dir)?.difference(&expected) {
        let path = generated_dir.join(relative);
        fs::remove_file(&path)
            .with_context(|| format!("removing stale generated doc {}", path.display()))?;
    }
    Ok(())
}

fn generated_files(generated_dir: &Path) -> Result<BTreeSet<String>> {
    let mut out = BTreeSet::new();
    if !generated_dir.exists() {
        return Ok(out);
    }
    collect_generated_files(generated_dir, generated_dir, &mut out)?;
    Ok(out)
}

fn collect_generated_files(root: &Path, dir: &Path, out: &mut BTreeSet<String>) -> Result<()> {
    let mut entries = fs::read_dir(dir)
        .with_context(|| format!("listing generated docs dir {}", dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()
        .with_context(|| format!("reading generated docs dir {}", dir.display()))?;
    entries.sort_by_key(|entry| entry.path());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_generated_files(root, &path, out)?;
        } else {
            out.insert(relative_path(root, &path)?);
        }
    }
    Ok(())
}

fn validate_generated_headers(docs: &GeneratedDocs) -> Result<()> {
    for (relative, content) in docs {
        validate_generated_marker(relative, content)?;
    }
    Ok(())
}

fn validate_generated_marker(relative: &str, content: &str) -> Result<()> {
    if relative.ends_with(".json") {
        let value: serde_json::Value = serde_json::from_str(content)
            .with_context(|| format!("parsing generated JSON marker for {relative}"))?;
        let generated_by = value
            .get("generated_by")
            .and_then(serde_json::Value::as_str);
        if generated_by != Some(structured::JSON_GENERATED_BY) {
            bail!("generated JSON marker missing or invalid at {GENERATED_DIR}/{relative}");
        }
    } else if !content.starts_with(HEADER) {
        bail!("generated doc header missing or invalid at {GENERATED_DIR}/{relative}");
    }
    Ok(())
}

fn validate_generated_line_cap(docs: &GeneratedDocs) -> Result<()> {
    for (relative, content) in docs {
        let line_count = content.lines().count();
        if line_count > LINE_CAP {
            bail!(
                "generated doc {}/{} has {} lines; split it below {} lines",
                GENERATED_DIR,
                relative,
                line_count,
                LINE_CAP
            );
        }
    }
    Ok(())
}

fn write_readme() -> String {
    let mut out = new_doc("Generated Documentation");
    out.push_str("Generated docs own mechanical facts derived from the source tree.\n");
    out.push_str("Handwritten docs own intent, invariants, trade-offs, and behavior.\n\n");
    out.push_str("| Question | Generated file |\n");
    out.push_str("|---|---|\n");
    out.push_str("| Workspace crates and dependencies | `CRATES.md` |\n");
    out.push_str("| Machine-readable generated manifest | `index.json` |\n");
    out.push_str("| Compact repo and localization map | `REPO_MAP.md` |\n");
    out.push_str("| Compact source/doc/test layout | `FILE_TREE.md` |\n");
    out.push_str("| File length and README signals | `FILE_HEALTH.md` |\n");
    out.push_str("| Registered commands and default key chords | `COMMANDS.md` |\n");
    out.push_str("| Settings fields, types, defaults, docs | `SETTINGS.md` |\n");
    out.push_str("| xtask commands, hooks, CI, perf gates | `GATES.md` |\n");
    out.push_str("| Unit/integration/bench/e2e/canary test inventory | `TEST_INDEX.md` |\n");
    out.push_str("| Theme key coverage and typed accessors | `THEME_KEYS.md` |\n");
    out.push_str("| SQLite persistence schema tables/indexes | `PERSIST_SCHEMA.md` |\n");
    out.push_str("| Thread/message/event enum variants | `MESSAGES.md` |\n");
    out.push_str("| Selection edit variants and planner routing | `SELECTION_EDITS.md` |\n");
    out.push_str("| Per-crate module/file inventory | `modules/<crate>.md` |\n");
    out.push_str("| Per-crate public API inventory | `api/<crate>.md` |\n");
    out.push_str("| Per-crate symbol localization | `symbols/<crate>.md` |\n\n");
    out.push_str("Run `cargo xtask docs` to regenerate. Run `cargo xtask docs-check` to fail on drift or stale Markdown routes.\n");
    out
}

pub(crate) fn new_doc(title: &str) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# ");
    out.push_str(title);
    out.push_str("\n\n");
    out
}

pub(crate) fn relative_path(root: &Path, path: &Path) -> Result<String> {
    let relative = path
        .strip_prefix(root)
        .with_context(|| format!("{} is not under {}", path.display(), root.display()))?;
    Ok(normalize_path(relative))
}

pub(crate) fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(crate) fn escape_md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

pub(crate) fn line_count(text: &str) -> usize {
    text.lines().count()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_readme_has_header() {
        assert!(write_readme().starts_with(HEADER));
    }

    #[test]
    fn generated_readme_stays_under_line_cap() {
        let mut docs = GeneratedDocs::new();
        docs.insert("README.md".into(), write_readme());
        validate_generated_line_cap(&docs).expect("line cap ok");
    }
}
